---
- name: Initialize OS setting for Linux Servers
  hosts: all 
  become: yes
  roles:
    - name: common/locale
    - name: common/selinux
    - name: common/firewalld
    - name: common/ipv6
    - name: common/chrony
    - name: common/rsyslog
    - name: common/logrotate

- name: Initialize Webservers setting
  hosts: webservers
  become: yes
  roles:
    - name: tomcat

- name: Initialize DBservers setting
  hosts: dbservers
  become: yes
  roles:
    - name: mysql
